BEGIN;
--
-- Creates extension ltree
--
-- (no-op)
--
-- Create model Author
--
CREATE TABLE "authors" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "uuid" uuid NOT NULL UNIQUE, "first_names" varchar(200) NOT NULL, "last_name" varchar(200) NOT NULL, "date_of_birth" date NOT NULL, "date_of_death" date NULL, "summary" text NOT NULL);
--
-- Create model Book
--
CREATE TABLE "books" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "uuid" uuid NOT NULL UNIQUE, "title" varchar(200) NOT NULL, "pages" integer NOT NULL, "introductory_pages" varchar(50) NULL, "width_in_cm" integer NULL, "length_in_cm" integer NULL, "cover" integer NULL, "weight_in_gr" integer NULL, "paper" integer NULL, "isbn" varchar(13) NULL, "edition" smallint NULL, "series" varchar(200) NULL, "volume" smallint NULL, "publication_date" date NOT NULL, "language" varchar(2) NOT NULL);
--
-- Create model Genre
--
CREATE TABLE "genres" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "uuid" uuid NOT NULL UNIQUE, "parent_id" integer NULL, "root_id" integer NOT NULL, "name" varchar(100) NOT NULL);
--
-- Create model Publisher
--
CREATE TABLE "publishers" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "uuid" uuid NOT NULL UNIQUE, "name" varchar(200) NOT NULL);
--
-- Create model BookAuthor
--
CREATE TABLE "book_authors" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "role" integer NOT NULL, "author_id" bigint NOT NULL, "book_id" bigint NOT NULL);
--
-- Create model BookGenre
--
CREATE TABLE "book_genres" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "book_id" bigint NOT NULL, "genre_id" bigint NOT NULL);
--
-- Add field publisher to book
--
ALTER TABLE "books" ADD COLUMN "publisher_id" bigint NOT NULL CONSTRAINT "books_publisher_id_8625a46d_fk_publishers_id" REFERENCES "publishers"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "books_publisher_id_8625a46d_fk_publishers_id" IMMEDIATE;
ALTER TABLE "book_authors" ADD CONSTRAINT "book_authors_author_id_ea39dbe4_fk_authors_id" FOREIGN KEY ("author_id") REFERENCES "authors" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "book_authors" ADD CONSTRAINT "book_authors_book_id_a678937d_fk_books_id" FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "book_authors_author_id_ea39dbe4" ON "book_authors" ("author_id");
CREATE INDEX "book_authors_book_id_a678937d" ON "book_authors" ("book_id");
ALTER TABLE "book_genres" ADD CONSTRAINT "book_genres_book_id_4c6da802_fk_books_id" FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "book_genres" ADD CONSTRAINT "book_genres_genre_id_63d275f3_fk_genres_id" FOREIGN KEY ("genre_id") REFERENCES "genres" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "book_genres_book_id_4c6da802" ON "book_genres" ("book_id");
CREATE INDEX "book_genres_genre_id_63d275f3" ON "book_genres" ("genre_id");
CREATE INDEX "books_publisher_id_8625a46d" ON "books" ("publisher_id");
COMMIT;
