# Generated by Django 5.2 on 2025-05-08 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("first_names", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("date_of_death", models.DateField(null=True)),
                ("summary", models.TextField()),
            ],
            options={
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("pages", models.IntegerField()),
                ("introductory_pages", models.CharField(max_length=50, null=True)),
                ("width_in_cm", models.IntegerField(null=True)),
                ("length_in_cm", models.IntegerField(null=True)),
                (
                    "cover",
                    models.IntegerField(
                        choices=[(1, "Paperback"), (2, "Hardback")], null=True
                    ),
                ),
                ("weight_in_gr", models.IntegerField(null=True)),
                (
                    "paper",
                    models.IntegerField(
                        choices=[(1, "Chamois"), (2, "Palatina")], null=True
                    ),
                ),
                ("isbn", models.CharField(max_length=13, null=True)),
                ("edition", models.SmallIntegerField(null=True)),
                ("series", models.CharField(max_length=200, null=True)),
                ("volume", models.SmallIntegerField(null=True)),
                ("publication_date", models.DateField()),
                (
                    "language",
                    models.CharField(
                        choices=[("GR", "Greek"), ("EN", "English")], max_length=2
                    ),
                ),
            ],
            options={
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("parent_id", models.IntegerField(null=True)),
                ("root_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "publishers",
            },
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (1, "Author"),
                            (2, "Translator"),
                            (3, "Editor"),
                            (4, "Series Editor"),
                            (5, "Introduction"),
                            (6, "Anthologist"),
                        ]
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.author"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "db_table": "book_authors",
            },
        ),
        migrations.CreateModel(
            name="BookGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.genre"
                    ),
                ),
            ],
            options={
                "db_table": "book_genres",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.publisher"
            ),
        ),
    ]
