# Generated by Django 5.2 on 2025-05-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.IntegerField(
                blank=True, choices=[(1, "Paperback"), (2, "Hardback")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="edition",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="introductory_pages",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="length_in_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="paper",
            field=models.IntegerField(
                blank=True, choices=[(1, "Chamois"), (2, "Palatina")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="series",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="volume",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="weight_in_gr",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="width_in_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="parent_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
