# Generated by Django 5.2 on 2025-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_author_date_of_death_alter_book_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                through="books.BookGenre",
                through_fields=("book", "genre"),
                to="books.genre",
            ),
        ),
    ]
