# Generated by Django 5.2 on 2025-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                through="books.BookAuthor",
                through_fields=("book", "author"),
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
