BEGIN;
--
-- Create model GenreNode
--
CREATE TABLE "genre_nodes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(180) NOT NULL, "path" ltree NOT NULL);
--
-- Change Meta options on author
--
-- (no-op)
--
-- Change Meta options on book
--
-- (no-op)
--
-- Change Meta options on genre
--
-- (no-op)
--
-- Change Meta options on publisher
--
-- (no-op)
--
-- Alter field authors on book
--
-- (no-op)
--
-- Alter field genres on book
--
-- (no-op)
COMMIT;
