BEGIN;
--
-- Change Meta options on author
--
-- (no-op)
--
-- Change Meta options on book
--
-- (no-op)
--
-- Change Meta options on genre
--
-- (no-op)
--
-- Change Meta options on publisher
--
-- (no-op)
--
-- Remove field parent_id from genre
--
ALTER TABLE "genres" DROP COLUMN "parent_id" CASCADE;
--
-- Remove field root_id from genre
--
ALTER TABLE "genres" DROP COLUMN "root_id" CASCADE;
--
-- Alter field authors on book
--
-- (no-op)
--
-- Alter field genres on book
--
-- (no-op)
--
-- Create model GenreChild
--
CREATE TABLE "genre_children" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "child_id" integer NOT NULL, "genre_id" bigint NOT NULL);
ALTER TABLE "genre_children" ADD CONSTRAINT "genre_children_genre_id_dd01ba39_fk_genres_id" FOREIGN KEY ("genre_id") REFERENCES "genres" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "genre_children_genre_id_dd01ba39" ON "genre_children" ("genre_id");
COMMIT;
