# Generated by Django 5.2 on 2025-05-30 16:45

import django_ltree.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_authors_alter_author_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenreNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("path", django_ltree.fields.PathField()),
            ],
            options={
                "db_table": "genre_nodes",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["last_name"]},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="authors",
                through="books.BookAuthor",
                through_fields=("book", "author"),
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                related_name="genres",
                through="books.BookGenre",
                through_fields=("book", "genre"),
                to="books.genre",
            ),
        ),
    ]
